### ISSUE TITLE
Déploiement

### ISSUE THREAD

**Issue by F9T** [HE-Arc/clonebnb#28]
Déploiement du site

**Comment by F9T** [comment]
Fonctionnel

**Comment by grunenwald** [comment]
Où ça ?

**Comment by F9T** [comment]
https://clonebnb.srvz-webapp.he-arc.ch

**Comment by F9T** [comment]
Encore quelques problèmes d'affichage.

**Comment by grunenwald** [comment]
mixed-content ?
APP_URL ?
secure-assets() ?

**Comment by F9T** [comment]
Merci, je vais voir ces points.

**Comment by F9T** [comment]
Effectivement, il manquait quelques secure-assets dans le css et le javascript. Merci

**Comment by F9T** [comment]
Encore quelques petits détails, mais le gros est fait. A corriger dans le code encore.

**Comment by greut** [comment]
Localisation ~ Lieu. https://fr.wiktionary.org/wiki/localisation
